# Generated by Django 3.2.6 on 2021-08-31 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('suhu', models.IntegerField()),
                ('hujan', models.IntegerField()),
                ('angin', models.IntegerField()),
                ('sungai', models.IntegerField(default=0)),
                ('kelembaban', models.IntegerField(default=0)),
                ('ketinggian_sungai', models.IntegerField(default=0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
        ),
    ]
